// util/dummyData.js
export const leaderboardData = [
    { id: '1', name: 'Alice', score: 150, age: 25, occupation: 'Engineer', dailyCarbonFootprint: '10 kg' },
    { id: '2', name: 'Bob', score: 140, age: 30, occupation: 'Designer', dailyCarbonFootprint: '12 kg' },
    { id: '3', name: 'Charlie', score: 130, age: 28, occupation: 'Teacher', dailyCarbonFootprint: '8 kg' },
    { id: '4', name: 'David', score: 120, age: 35, occupation: 'Developer', dailyCarbonFootprint: '15 kg' },
    { id: '5', name: 'Eve', score: 110, age: 22, occupation: 'Student', dailyCarbonFootprint: '7 kg' },
  ];
  

// util/offsetCarbonData.js
export const offsetCarbonData = {
    latest: [
      { id: '1', title: 'Plant Trees', image: require('../assets/tree.jpg'), description: 'Plant 100 trees to offset carbon.' },
      { id: '2', title: 'Solar Panels', image: require('../assets/solar.jpg'), description: 'Install solar panels in your home.' },
      { id: '3', title: 'Bike to Work', image: require('../assets/bike.jpg'), description: 'Use a bike for your daily commute.' },
      { id: '4', title: 'Recycle', image: require('../assets/recycle.jpg'), description: 'Participate in recycling programs.' },
      { id: '5', title: 'Use Public Transport', image: require('../assets/public_transport.jpg'), description: 'Reduce carbon footprint by using public transport.' },
    ],
    older: [
      { id: '6', title: 'Carpool', image: require('../assets/carpool.jpg'), description: 'Share rides with colleagues.' },
      { id: '7', title: 'Energy Efficient Appliances', image: require('../assets/energy_efficient.jpg'), description: 'Upgrade to energy-efficient appliances.' },
      { id: '8', title: 'Compost', image: require('../assets/compost.jpg'), description: 'Compost kitchen waste to reduce landfill.' },
      { id: '9', title: 'Reduce Meat Consumption', image: require('../assets/reduce_meat.jpg'), description: 'Cut down on meat to lower carbon footprint.' },
      { id: '10', title: 'Plant-Based Diet', image: require('../assets/plant_based.jpg'), description: 'Adopt a plant-based diet.' },
    ]
  };
  
// util/dummyData.js (or util/ecoChallengesData.js)
// util/dummyData.js (or util/ecoChallengesData.js)
export const ecoChallengesDataWeek = [
  {
    id: '1',
    taskNo: 1,
    name: 'Paperless Week Challenge',
    challenge: 'Go completely paperless for a week by using digital alternatives for documents, receipts, and notes.',
    benefitsToSociety: 'Supports the Digital India Mission by reducing deforestation and saving energy.',
    points: 5,
    image: require('../assets/Eco-challenges/Challenges/paperless.jpeg'),
    timeline: '1 Week',
    requiredImage: 3,  // Count of required images
    carbonEmission: '-5 kg CO2',
  },
  {
    id: '2',
    taskNo: 2,
    name: 'Meat-Free Week Challenge',
    challenge: 'Avoid meat for the entire week, opting for plant-based meals instead.',
    benefitsToSociety: 'Supports the National Nutrition Mission by reducing the carbon footprint of livestock farming.',
    points: 10,
    image: require('../assets/Eco-challenges/Challenges/plant_based.jpeg'),
    timeline: '1 Week',
    requiredImage: 5,  // Count of required images
    carbonEmission: '-10 kg CO2',
  },
  {
    id: '3',
    taskNo: 3,
    name: 'Community Cleanup Week',
    challenge: 'Organize or participate in community cleanups for an hour each day of the week.',
    benefitsToSociety: 'Supports the Swachh Bharat Mission by reducing pollution and methane emissions from landfills.',
    points: 8,
    image: require('../assets/Eco-challenges/Challenges/cleanup.jpeg'),
    timeline: '1 Week',
    requiredImage: 4,  // Count of required images
    carbonEmission: '-8 kg CO2',
  },
  {
    id: '4',
    taskNo: 4,
    name: 'Local Shopping Week',
    challenge: 'Purchase all groceries and essentials from local vendors for the week, avoiding large retail chains.',
    benefitsToSociety: 'Supports Atmanirbhar Bharat by promoting local economies and reducing transportation emissions.',
    points: 5,
    image: require('../assets/Eco-challenges/Challenges/local_shopping.jpeg'),
    timeline: '1 Week',
    requiredImage: 3,  // Count of required images
    carbonEmission: '-5 kg CO2',
  },
  {
    id: '5',
    taskNo: 5,
    name: 'Reusable Cup and Bottle Week',
    challenge: 'Use a reusable cup and water bottle instead of single-use options every day for a week.',
    benefitsToSociety: 'Supports Plastic Waste Management Rules by preventing plastic waste and reducing carbon footprint.',
    points: 3,
    image: require('../assets/Eco-challenges/Challenges/reusable_cup_bottle.jpeg'),
    timeline: '1 Week',
    requiredImage: 2,  // Count of required images
    carbonEmission: '-3 kg CO2',
  },
  {
    id: '6',
    taskNo: 6,
    name: 'Ride Sharing Week',
    challenge: 'Use ride-sharing, carpooling, or public transport for all trips during the week.',
    benefitsToSociety: 'Supports the FAME II Scheme by reducing the number of vehicles on the road and lowering emissions.',
    points: 6,
    image: require('../assets/Eco-challenges/Challenges/ride_sharing.jpeg'),
    timeline: '1 Week',
    requiredImage: 4,  // Count of required images
    carbonEmission: '-6 kg CO2',
  },
  {
    id: '7',
    taskNo: 7,
    name: 'Adopt a Reusable Shopping Bag',
    challenge: 'Use a reusable shopping bag for all purchases throughout the week, avoiding plastic bags entirely.',
    benefitsToSociety: 'Supports Plastic Waste Management Rules by reducing the environmental burden of plastic production.',
    points: 2,
    image: require('../assets/Eco-challenges/Challenges/reusable_bag.jpeg'),
    timeline: '1 Week',
    requiredImage: 2,  // Count of required images
    carbonEmission: '-2 kg CO2',
  },
];
// util/dummyData.js (or util/ecoChallengesData.js)
export const ecoChallengesDataMonth = [
  {
    id: '1',
    taskNo: 1,
    name: 'Adopt a Tree Campaign',
    challenge: 'Plant and maintain at least 5 trees.',
    benefitsToSociety: 'Aligns with the National Mission for a Green India by contributing to long-term carbon sequestration.',
    points: 10,
    image: require('../assets/Eco-challenges/Challenges/adopt_tree.jpeg'),
    timeline: '1 Month',
    requiredImage: 3,  // Number of images required
    carbonEmission: '-50 kg CO2 (10 kg per tree)',
  },
  {
    id: '2',
    taskNo: 2,
    name: 'Switch to Renewable Energy',
    challenge: 'Replace 20% of your energy usage with renewable sources like solar or wind.',
    benefitsToSociety: 'Supports the Ministry of New and Renewable Energy and IREDA by reducing reliance on fossil fuels.',
    points: 50,
    image: require('../assets/Eco-challenges/Challenges//renewable_energy.jpeg'),
    timeline: '1 Month',
    requiredImage: 2,
    carbonEmission: '-50 kg CO2',
  },
  {
    id: '3',
    taskNo: 3,
    name: 'Zero-Waste Challenge',
    challenge: 'Produce less than 1 kg of waste for the month by reusing, recycling, and composting.',
    benefitsToSociety: 'Supports the Swachh Bharat Mission by reducing methane emissions from landfills.',
    points: 5,
    image: require('../assets/Eco-challenges/Challenges//zero_waste.jpeg'),
    timeline: '1 Month',
    requiredImage: 4,
    carbonEmission: '-5 kg CO2 for every kg of waste avoided',
  },
  {
    id: '4',
    taskNo: 4,
    name: 'Smart Commuting',
    challenge: 'Use public transport or shared rides for 80% of your commutes.',
    benefitsToSociety: 'Supports FAME II and Smart Cities Mission by reducing emissions per person.',
    points: 100,
    image: require('../assets/Eco-challenges/Challenges//smart_commuting.jpeg'),
    timeline: '1 Month',
    requiredImage: 3,
    carbonEmission: '-100 kg CO2',
  },
  {
    id: '5',
    taskNo: 5,
    name: 'Reduce Electricity Usage',
    challenge: 'Reduce your electricity consumption by 15%.',
    benefitsToSociety: 'Supports the Perform, Achieve, and Trade (PAT) Scheme by lowering the demand for fossil fuels.',
    points: 50,
    image: require('../assets/Eco-challenges/Challenges//reduce_electricity.jpeg'),
    timeline: '1 Month',
    requiredImage: 2,
    carbonEmission: '-50 kg CO2',
  },
  {
    id: '6',
    taskNo: 6,
    name: 'Water Conservation',
    challenge: 'Reduce water usage by 25% by using water-saving devices or rainwater harvesting.',
    benefitsToSociety: 'Supports AMRUT and Smart Cities Mission by reducing energy use for water treatment.',
    points: 10,
    image: require('../assets/Eco-challenges/Challenges//water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 2,
    carbonEmission: '-10 kg CO2',
  },
  {
    id: '7',
    taskNo: 7,
    name: 'Carbon Footprint Tracking',
    challenge: 'Track and reduce your carbon footprint by 20% for the month.',
    benefitsToSociety: 'Supports MoEFCC and CPCB by raising awareness about individual carbon emissions.',
    points: 20,
    image: require('../assets/Eco-challenges/Challenges//water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 1,
    carbonEmission: '-20 kg CO2',
  },
  {
    id: '8',
    taskNo: 8,
    name: 'Green Office Challenge',
    challenge: 'Implement at least 5 eco-friendly practices in your office.',
    benefitsToSociety: 'Supports Bureau of Energy Efficiency (BEE) by reducing energy consumption in workplaces.',
    points: 50,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 3,
    carbonEmission: '-50 kg CO2',
  },
  {
    id: '9',
    taskNo: 9,
    name: 'Plastic-Free Living Challenge',
    challenge: 'Avoid single-use plastics for the entire month by using reusable alternatives.',
    benefitsToSociety: 'Supports Plastic Waste Management Rules by reducing waste and emissions.',
    points: 10,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 4,
    carbonEmission: '-10 kg CO2',
  },
  {
    id: '10',
    taskNo: 10,
    name: 'Install Rainwater Harvesting System',
    challenge: 'Install a rainwater harvesting system at home or office.',
    benefitsToSociety: 'Supports AMRUT and Jal Shakti Mission by reducing dependency on centralized water supply.',
    points: 15,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 2,
    carbonEmission: '-15 kg CO2',
  },
  {
    id: '11',
    taskNo: 11,
    name: 'Efficient Lighting Challenge',
    challenge: 'Replace all lighting in your home or office with energy-efficient LEDs.',
    benefitsToSociety: 'Supports Ujala and PAT Schemes by reducing energy consumption.',
    points: 20,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 2,
    carbonEmission: '-20 kg CO2',
  },
  {
    id: '12',
    taskNo: 12,
    name: 'Switch to Organic Farming',
    challenge: 'Practice organic farming or sustainable gardening for 3 months.',
    benefitsToSociety: 'Supports Paramparagat Krishi Vikas Yojana by reducing the use of synthetic fertilizers.',
    points: 25,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Months',
    requiredImage: 4,
    carbonEmission: '-25 kg CO2',
  },
  {
    id: '13',
    taskNo: 13,
    name: 'Air Quality Monitoring Challenge',
    challenge: 'Install and use an air quality monitor at home or office.',
    benefitsToSociety: 'Supports the National Clean Air Programme by raising awareness of pollution levels.',
    points: 5,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 1,
    carbonEmission: '-5 kg CO2',
  },
  {
    id: '14',
    taskNo: 14,
    name: 'Adopt Electric Vehicles',
    challenge: 'Replace a petrol or diesel vehicle with an electric vehicle (EV) for commuting and personal use.',
    benefitsToSociety: 'Supports the FAME II Scheme by significantly reducing CO2 emissions.',
    points: 100,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 3,
    carbonEmission: '-100 kg CO2',
  },
  {
    id: '15',
    taskNo: 15,
    name: 'Solar Panel Installation',
    challenge: 'Install solar panels at your home or office and track energy usage over 3 months.',
    benefitsToSociety: 'Supports the Jawaharlal Nehru National Solar Mission by reducing reliance on fossil fuels.',
    points: 200,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Months',
    requiredImage: 4,
    carbonEmission: '-200 kg CO2',
  },
  {
    id: '16',
    taskNo: 16,
    name: 'Green Tech Adoption',
    challenge: 'Install energy-efficient appliances (air conditioners, refrigerators, or heaters) in your home or office.',
    benefitsToSociety: 'Aligns with the Bureau of Energy Efficiency’s Standards & Labeling Programme.',
    points: 50,
    image: require('../assets/Eco-challenges/Challenges/water_conservation.jpeg'),
    timeline: '1 Month',
    requiredImage: 2,
    carbonEmission: '-50 kg CO2',
  },
];


  // countries.js
export const countries = [
  { code: "None", name: "Select", flag: "none" },
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
];

export const states = {
  US: [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 
    'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
    'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 
    'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
    'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
    'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
    'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
    'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
    'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming',
    'Washington, D.C.' // Federal District
  ],
  IN: [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
    'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
    'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
    'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
    'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
    'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 
    'Lakshadweep', 'Delhi', 'Puducherry', 'Ladakh', 'Jammu and Kashmir'
  ],
  
  // Add other countries and their states here
};


